version: '2'
services:
    pis-app:
        image: pis
        external_links:
            - pis-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/pis?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    pis-mysql:
        extends:
            file: mysql.yml
            service: pis-mysql
